# obsidian_path := "~/Documents/obsidian/"

date_string := "+%Y-%m-%d"
tasknotes_cli := "mtnb"

alias lt := log-timer
alias lw := log-week

[arg("from", help="The beginning date")]
[doc("Log TaskNotes Pomodoro entries from a specific date (default to today)")]
log-timer from="today":
    {{ tasknotes_cli }} timer log --from "$(date -d '{{ from }}' '{{ date_string }}')" --to "$(date '{{ date_string }}')" 

[doc("Log TaskNotes Pomodoro entries for the current week (Monday to Today)")]
log-week:
    {{ tasknotes_cli }} timer log --from "$(date -d 'last monday' '{{ date_string }}')" --to "$(date '{{ date_string }}')"
