### Config for remote ssh servers. Copy into `~/.config/tmux/tmux.conf` ###

# status bar
set-option -g status-position top

# default shell
set-option -g default-shell /usr/bin/zsh

# Start windows and panes at 2, not 0
set -g base-index 1
set -g pane-base-index 1

# Change the default $TERM to tmux-256color
# Use tmux-256color inside tmux for best compatibility
set -g default-terminal "tmux-256color"
# Enable RGB colour if running in xterm(1) (so colors are same with or without tmux)
# See https://stackoverflow.com/questions/60923257/tmux-how-to-copy-text-between-nested-remote-ssh-session-and-local-machine
set -sa terminal-overrides ",xterm*:Tc:sitm=\E[3m"
# Enable clipboard to outer tmux session for nested tmux session
set -as terminal-overrides ',tmux*:Ms=\\E]52;%p1%s;%p2%s\\007'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colors - needs tmux-3.0

# Turn the mouse on, but without copy mode dragging
set -g mouse on
# unbind -n MouseDrag1Pane
# unbind -T copy-mode MouseDrag1Pane

# Allow Yazi image preview
# set -g allow-passthrough on
# set -ga update-environment TERM
# set -ga update-environment TERM_PROGRAM

# Enable extended keys for compatibility
set -s extended-keys always
set -as terminal-features 'xterm*:extkeys'

# set vi-mode
set-option -g status-keys vi		# Use Vi bindings in tmux command prompt.
set-window-option -g mode-keys vi	# Use Vi bindings in copy and choice mode.
# keybindings
bind v copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection

# Open panes in current directory
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt

# Reload tmux (already done by tmux-powerkit plugin)
unbind r
# source config file
bind r source-file ~/.config/tmux/tmux.conf \; display-message "█▓░ reloaded"

# Pane movements
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# set -g @plugin 'laktak/extrakto'
set -g @plugin 'trevin-j/tmux-resurrect-nvim'
set -g @plugin 'tmux-plugins/tmux-continuum'
 
# Continuum
## Last saved environment is automatically restored when tmux is started.
set -g @continuum-restore 'on'
## Tmux automatically started after the computer is turned on
# set -g @continuum-boot 'on'


#Check if tpm is installed, if not install it and other plugins as well
if-shell "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'" \

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

